[project]
name = "metabiantes"
version = "0.1.0"
description = "An ORM-based database of metabolic information"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "sqlalchemy[asyncio]",
    "aiosqlite",
    "pythoncyc",
]
[project.optional-dependencies]
lint = [
    "ruff",
    "flake8",
    "black",
    "isort",
    "mypy",
    "pyright"
]
doc = [
    "sphinx"
]
